services:
  rsn-cartographie:
    build: .
    container_name: rsn-cartographie
    ports:
      - "13080:3000"
    environment:
      - NODE_ENV=production
      # - NEXT_PUBLIC_API_URL="https://prevalis-web1.fmss.usherbrooke.ca/rsn/cartographie"
    restart: unless-stopped
